version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:123123@db:5432/postgres
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
