apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  ports:
    - port: 8080
  selector:
    app: cptexcapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cptexcapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cptexcapi
  template:
    metadata:
      labels:
        app: cptexcapi
    spec:
      containers:
      - name: cptexcapi
        image: cptexcapi:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
          - name: FLASK_APP
            value: "main.py"
          - name: FLASK_ENV
            value: "development"
          - name: DATABASE_HOST
            value: "postgres"
          - name: DATABASE_PORT
            value: "5432"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          env:
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "123123"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30000
  selector:
    app: cptexcapi
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cptexcapi-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cptexcapi-deployment
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 90
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-app-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: "135.181.47.96.nip.io"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: web-app-service
            port:
              number: 8080
